# Generated by Django 2.2 on 2019-08-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20190803_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items_order',
            field=models.ManyToManyField(to='shop.CartItem'),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='shop.Cart'),
        ),
    ]
