# Generated by Django 2.2 on 2019-08-03 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20190803_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='items_order',
            new_name='items_in_order',
        ),
    ]
