# Generated by Django 2.2 on 2019-08-03 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_remove_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items_in_order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Cart'),
        ),
    ]
