# Generated by Django 2.2 on 2019-08-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20190803_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items_in_order',
            field=models.ManyToManyField(to='shop.CartItem'),
        ),
    ]
