# Generated by Django 2.2 on 2019-08-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_order_items_in_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items_in_order',
        ),
        migrations.AddField(
            model_name='order',
            name='items_in_order',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
    ]
